import { createClientFromRequest } from 'npm:@api/sdk@0.8.6';
import { jsPDF } from 'npm:jspdf@2.5.1';

Deno.serve(async (req) => {
  try {
    const api = createClientFromRequest(req);
    
    const user = await api.auth.me();
    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { filters, format } = await req.json();

    // Fetch patients with filters
    let patients = await api.entities.Patient.list('-priority_score', 1000);

    // Apply filters
    if (filters) {
      if (filters.organ && filters.organ !== 'all') {
        patients = patients.filter(p => p.organ_needed === filters.organ);
      }
      if (filters.bloodType && filters.bloodType !== 'all') {
        patients = patients.filter(p => p.blood_type === filters.bloodType);
      }
      if (filters.status && filters.status !== 'all') {
        patients = patients.filter(p => p.waitlist_status === filters.status);
      }
      if (filters.search) {
        const search = filters.search.toLowerCase();
        patients = patients.filter(p =>
          p.first_name?.toLowerCase().includes(search) ||
          p.last_name?.toLowerCase().includes(search) ||
          p.patient_id?.toLowerCase().includes(search)
        );
      }
    }

    if (format === 'csv') {
      // Generate CSV
      const headers = [
        'Patient ID',
        'Name',
        'Blood Type',
        'Organ Needed',
        'Priority Score',
        'Medical Urgency',
        'Status',
        'Days on Waitlist',
        'Last Evaluation',
      ];

      const rows = patients.map(p => {
        const daysOnList = p.date_added_to_waitlist
          ? Math.floor((new Date() - new Date(p.date_added_to_waitlist)) / (1000 * 60 * 60 * 24))
          : 0;
        
        return [
          p.patient_id,
          `${p.first_name} ${p.last_name}`,
          p.blood_type,
          p.organ_needed,
          (p.priority_score || 0).toFixed(1),
          p.medical_urgency,
          p.waitlist_status,
          daysOnList,
          p.last_evaluation_date || 'N/A',
        ];
      });

      const csvContent = [
        headers.join(','),
        ...rows.map(row => row.map(cell => `"${cell}"`).join(',')),
      ].join('\n');

      // Log export
      await api.entities.AuditLog.create({
        action: 'export',
        entity_type: 'Waitlist',
        details: `Exported ${patients.length} patients to CSV`,
        user_email: user.email,
        user_role: user.role,
      });

      return new Response(csvContent, {
        headers: {
          'Content-Type': 'text/csv',
          'Content-Disposition': `attachment; filename="waitlist-export-${new Date().toISOString().split('T')[0]}.csv"`,
        },
      });
    } else {
      // Generate PDF
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();

      // Title
      doc.setFontSize(20);
      doc.setTextColor(8, 145, 178);
      doc.text('TransTrack Waitlist Report', 20, 20);

      // Metadata
      doc.setFontSize(10);
      doc.setTextColor(100);
      doc.text(`Generated: ${new Date().toLocaleString()}`, 20, 30);
      doc.text(`Total Patients: ${patients.length}`, 20, 36);
      doc.text(`Generated by: ${user.full_name}`, 20, 42);

      let y = 55;

      patients.forEach((patient, index) => {
        // Check if we need a new page
        if (y > pageHeight - 40) {
          doc.addPage();
          y = 20;
        }

        // Patient box
        const boxHeight = 35;
        
        // Priority color bar
        const score = patient.priority_score || 0;
        let color;
        if (score >= 80) color = [220, 38, 38];
        else if (score >= 60) color = [249, 115, 22];
        else if (score >= 40) color = [245, 158, 11];
        else color = [100, 116, 139];

        doc.setFillColor(color[0], color[1], color[2]);
        doc.rect(20, y, 3, boxHeight, 'F');

        // Background box
        doc.setFillColor(249, 250, 251);
        doc.rect(23, y, pageWidth - 43, boxHeight, 'F');

        // Patient info
        doc.setFontSize(12);
        doc.setTextColor(0);
        doc.setFont(undefined, 'bold');
        doc.text(`${patient.first_name} ${patient.last_name}`, 28, y + 7);
        
        doc.setFont(undefined, 'normal');
        doc.setFontSize(9);
        doc.setTextColor(100);
        doc.text(`ID: ${patient.patient_id}`, 28, y + 13);

        doc.text(`Organ: ${patient.organ_needed}`, 28, y + 19);
        doc.text(`Blood: ${patient.blood_type}`, 28, y + 25);
        doc.text(`Status: ${patient.waitlist_status}`, 28, y + 31);

        // Priority score
        doc.setFontSize(16);
        doc.setTextColor(color[0], color[1], color[2]);
        doc.setFont(undefined, 'bold');
        doc.text(`${score.toFixed(0)}`, pageWidth - 35, y + 20);
        doc.setFontSize(8);
        doc.text('Priority', pageWidth - 35, y + 26);

        y += boxHeight + 5;
      });

      const pdfBytes = doc.output('arraybuffer');

      // Log export
      await api.entities.AuditLog.create({
        action: 'export',
        entity_type: 'Waitlist',
        details: `Exported ${patients.length} patients to PDF`,
        user_email: user.email,
        user_role: user.role,
      });

      return new Response(pdfBytes, {
        headers: {
          'Content-Type': 'application/pdf',
          'Content-Disposition': `attachment; filename="waitlist-report-${new Date().toISOString().split('T')[0]}.pdf"`,
        },
      });
    }
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});