/**
 * TransTrack — Publisher Ed25519 public key (license signature verification).
 *
 * This file ships in the production build. The corresponding private key
 * lives OFFLINE on the publisher's signing workstation and MUST NOT be
 * committed to the repository.
 *
 * KEY ROTATION:
 *   1. Generate a new keypair: `node scripts/license-keypair.mjs --force`
 *   2. Update PUBLIC_KEY_BASE64 below to the new value printed by the script.
 *   3. Bump LICENSE_PROTOCOL_VERSION so prior in-the-wild app builds reject
 *      licenses signed with the new key (and vice versa).
 *   4. Re-issue every active customer license signed with the new private key.
 *   5. Distribute the new build to customers (auto-update channel).
 *
 * BUILD-TIME OVERRIDE:
 *   For per-environment keys (staging vs production vs an offline pilot
 *   site that runs its own publisher), set the env var
 *   `TRANSTRACK_PUBLISHER_PUBLIC_KEY` at build time and electron-builder
 *   will bake it into the artifact. The default below is the development
 *   key generated by scripts/license-keypair.mjs.
 */

'use strict';

const DEV_PUBLIC_KEY_BASE64 = 'MHSe+m/IfhXeUSHXwk6AX+ArAOs495AatZ3zNkymgsI=';

const PUBLIC_KEY_BASE64 = process.env.TRANSTRACK_PUBLISHER_PUBLIC_KEY
  || DEV_PUBLIC_KEY_BASE64;

const LICENSE_PROTOCOL_VERSION = 1;

module.exports = {
  PUBLIC_KEY_BASE64,
  LICENSE_PROTOCOL_VERSION,
  IS_DEV_KEY: PUBLIC_KEY_BASE64 === DEV_PUBLIC_KEY_BASE64,
};
