/**
 * TransTrack — Publisher Ed25519 public key (license signature verification).
 *
 * This file ships in the production build. The corresponding private key
 * lives OFFLINE on the publisher's signing workstation and MUST NOT be
 * committed to the repository.
 *
 * KEY ROTATION:
 *   1. Generate a new keypair: `node scripts/license-keypair.mjs --force`
 *   2. Update PUBLIC_KEY_BASE64 below to the new value printed by the script.
 *   3. Bump LICENSE_PROTOCOL_VERSION so prior in-the-wild app builds reject
 *      licenses signed with the new key (and vice versa).
 *   4. Re-issue every active customer license signed with the new private key.
 *   5. Distribute the new build to customers (auto-update channel).
 *
 * BUILD-TIME OVERRIDE:
 *   For per-environment keys (staging vs production vs an offline pilot
 *   site that runs its own publisher), set the env var
 *   `TRANSTRACK_PUBLISHER_PUBLIC_KEY` at build time and electron-builder
 *   will bake it into the artifact. The default below is the development
 *   key generated by scripts/license-keypair.mjs.
 *
 * H-7: packaged builds refuse to run (and refuse to verify licenses) while
 * the embedded key is still the development key, unless an explicit
 * escape hatch is set for local packaged QA.
 */

'use strict';

const DEV_PUBLIC_KEY_BASE64 = 'MHSe+m/IfhXeUSHXwk6AX+ArAOs495AatZ3zNkymgsI=';

const PUBLIC_KEY_BASE64 = process.env.TRANSTRACK_PUBLISHER_PUBLIC_KEY
  || DEV_PUBLIC_KEY_BASE64;

const LICENSE_PROTOCOL_VERSION = 1;

const IS_DEV_KEY = PUBLIC_KEY_BASE64 === DEV_PUBLIC_KEY_BASE64;

function _isPackagedApp() {
  try {
    const { app } = require('electron');
    return Boolean(app && app.isPackaged);
  } catch {
    return false;
  }
}

/**
 * Fail closed when a packaged binary still trusts the repository's
 * development publisher key (H-7). Development / test / unpackaged runs
 * continue to use the DEV key so local workflows remain usable.
 *
 * Escape hatch (packaged QA only): TRANSTRACK_ALLOW_DEV_PUBLISHER=true
 */
function assertPublisherKeyAllowed(opts = {}) {
  const packaged = opts.packaged != null ? !!opts.packaged : _isPackagedApp();
  const allowDev =
    process.env.TRANSTRACK_ALLOW_DEV_PUBLISHER === 'true' ||
    opts.allowDevPublisher === true;
  if (packaged && IS_DEV_KEY && !allowDev) {
    const err = new Error(
      'This packaged build still embeds the development license publisher key. ' +
      'Set TRANSTRACK_PUBLISHER_PUBLIC_KEY to the production public key at build ' +
      'time (see docs/LICENSING.md). Refusing to start.'
    );
    err.code = 'DEV_PUBLISHER_KEY';
    throw err;
  }
  return true;
}

module.exports = {
  PUBLIC_KEY_BASE64,
  LICENSE_PROTOCOL_VERSION,
  IS_DEV_KEY,
  DEV_PUBLIC_KEY_BASE64,
  assertPublisherKeyAllowed,
};
