/**
 * TransTrack - Outcomes Tracking Service
 * 
 * Computes and records operational outcome metrics over configurable periods.
 * Used to demonstrate TransTrack ROI by measuring how risk detection and
 * proactive task management improve transplant center operations.
 * 
 * All calculations are performed locally on the encrypted SQLite database.
 */

const { getDatabase } = require('../database/init.cjs');
const { v4: uuidv4 } = require('uuid');
const { logger } = require('./logger.cjs');

function requireOrgId(orgId) {
  if (!orgId) throw new Error('Organization context required');
}

function computeOutcomesSnapshot(orgId, periodStart, periodEnd) {
  requireOrgId(orgId);
  const db = getDatabase();

  const activePatients = db.prepare(
    `SELECT COUNT(*) as count FROM patients WHERE org_id = ? AND waitlist_status = 'active'`
  ).get(orgId);

  const inactivations = db.prepare(
    `SELECT COUNT(*) as count FROM patients 
     WHERE org_id = ? AND waitlist_status = 'inactive' 
     AND updated_at BETWEEN ? AND ?`
  ).get(orgId, periodStart, periodEnd);

  const evalRenewed = db.prepare(
    `SELECT COUNT(*) as count FROM patients 
     WHERE org_id = ? AND last_evaluation_date BETWEEN ? AND ?`
  ).get(orgId, periodStart, periodEnd);

  const evalLapsed = db.prepare(
    `SELECT COUNT(*) as count FROM patients 
     WHERE org_id = ? AND waitlist_status = 'active' 
     AND last_evaluation_date IS NOT NULL 
     AND datetime(last_evaluation_date, '+365 days') < datetime('now')`
  ).get(orgId);

  const barriersResolved = db.prepare(
    `SELECT COUNT(*) as count FROM readiness_barriers 
     WHERE org_id = ? AND status = 'resolved' 
     AND resolved_date BETWEEN ? AND ?`
  ).get(orgId, periodStart, periodEnd);

  const barriersOpened = db.prepare(
    `SELECT COUNT(*) as count FROM readiness_barriers 
     WHERE org_id = ? AND created_at BETWEEN ? AND ?`
  ).get(orgId, periodStart, periodEnd);

  const avgResolution = db.prepare(
    `SELECT AVG(
       julianday(resolved_date) - julianday(identified_date)
     ) as avg_days FROM readiness_barriers 
     WHERE org_id = ? AND status = 'resolved' 
     AND resolved_date BETWEEN ? AND ?`
  ).get(orgId, periodStart, periodEnd);

  const riskAlerts = db.prepare(
    `SELECT COUNT(*) as count FROM notifications 
     WHERE org_id = ? AND notification_type IN ('risk_alert', 'evaluation_expiring', 'barrier_alert')
     AND created_at BETWEEN ? AND ?`
  ).get(orgId, periodStart, periodEnd);

  const riskAlertsActed = db.prepare(
    `SELECT COUNT(*) as count FROM notifications 
     WHERE org_id = ? AND notification_type IN ('risk_alert', 'evaluation_expiring', 'barrier_alert')
     AND is_read = 1 AND created_at BETWEEN ? AND ?`
  ).get(orgId, periodStart, periodEnd);

  let tasksAutoGenerated = 0;
  let tasksCompletedOnTime = 0;
  let tasksEscalated = 0;
  try {
    const taskStats = db.prepare(
      `SELECT 
         COUNT(*) as total,
         SUM(CASE WHEN source != 'MANUAL' THEN 1 ELSE 0 END) as auto_generated,
         SUM(CASE WHEN status = 'completed' AND (due_date IS NULL OR completed_date <= due_date) THEN 1 ELSE 0 END) as on_time,
         SUM(CASE WHEN escalation_level > 0 THEN 1 ELSE 0 END) as escalated
       FROM tasks WHERE org_id = ? AND created_at BETWEEN ? AND ?`
    ).get(orgId, periodStart, periodEnd);
    tasksAutoGenerated = taskStats?.auto_generated || 0;
    tasksCompletedOnTime = taskStats?.on_time || 0;
    tasksEscalated = taskStats?.escalated || 0;
  } catch (e) {
    logger.warn('Could not compute task stats for outcomes', { error: e.message });
  }

  const patientsAtRisk = db.prepare(
    `SELECT COUNT(*) as count FROM patients 
     WHERE org_id = ? AND waitlist_status = 'active'
     AND (
       (last_evaluation_date IS NOT NULL AND datetime(last_evaluation_date, '+335 days') < datetime('now'))
       OR updated_at < datetime('now', '-60 days')
     )`
  ).get(orgId);

  const totalActive = activePatients?.count || 0;
  const atRiskCount = patientsAtRisk?.count || 0;
  const atRiskPct = totalActive > 0 ? Math.round((atRiskCount / totalActive) * 1000) / 10 : 0;

  return {
    total_active_patients: totalActive,
    total_inactivations: inactivations?.count || 0,
    risk_alerts_with_resolution: Math.min(riskAlertsActed?.count || 0, riskAlerts?.count || 0),
    evaluations_renewed_on_time: evalRenewed?.count || 0,
    evaluations_lapsed: evalLapsed?.count || 0,
    avg_barrier_resolution_days: Math.round((avgResolution?.avg_days || 0) * 10) / 10,
    barriers_resolved: barriersResolved?.count || 0,
    barriers_opened: barriersOpened?.count || 0,
    avg_time_to_intervention_hours: 0,
    risk_alerts_generated: riskAlerts?.count || 0,
    risk_alerts_acted_on: riskAlertsActed?.count || 0,
    coordinator_load_std_dev: 0,
    patients_at_risk: atRiskCount,
    patients_at_risk_percentage: atRiskPct,
    tasks_auto_generated: tasksAutoGenerated,
    tasks_completed_on_time: tasksCompletedOnTime,
    tasks_escalated: tasksEscalated,
  };
}

function saveSnapshot(orgId, periodStart, periodEnd, createdBy) {
  requireOrgId(orgId);
  const db = getDatabase();
  const metrics = computeOutcomesSnapshot(orgId, periodStart, periodEnd);
  const id = uuidv4();

  const fields = ['id', 'org_id', 'period_start', 'period_end', 'created_by', ...Object.keys(metrics)];
  const values = [id, orgId, periodStart, periodEnd, createdBy, ...Object.values(metrics)];
  const placeholders = fields.map(() => '?').join(', ');

  db.prepare(`INSERT INTO outcomes_snapshots (${fields.join(', ')}) VALUES (${placeholders})`).run(...values);

  logger.info('Outcomes snapshot saved', { orgId, periodStart, periodEnd, id });
  return db.prepare('SELECT * FROM outcomes_snapshots WHERE id = ?').get(id);
}

function getSnapshots(orgId, limit = 12) {
  requireOrgId(orgId);
  const db = getDatabase();
  return db.prepare(
    `SELECT * FROM outcomes_snapshots WHERE org_id = ? ORDER BY snapshot_date DESC LIMIT ?`
  ).all(orgId, limit);
}

function getLatestSnapshot(orgId) {
  requireOrgId(orgId);
  const db = getDatabase();
  return db.prepare(
    `SELECT * FROM outcomes_snapshots WHERE org_id = ? ORDER BY snapshot_date DESC LIMIT 1`
  ).get(orgId) || null;
}

function getDashboard(orgId) {
  requireOrgId(orgId);
  const now = new Date();
  const thirtyDaysAgo = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000).toISOString();
  const ninetyDaysAgo = new Date(now.getTime() - 90 * 24 * 60 * 60 * 1000).toISOString();
  const nowStr = now.toISOString();

  const current = computeOutcomesSnapshot(orgId, thirtyDaysAgo, nowStr);
  const historical = getSnapshots(orgId, 6);

  const previous = historical.length > 0 ? historical[0] : null;

  const trends = {};
  if (previous) {
    const deltaKeys = [
      'total_inactivations', 'evaluations_lapsed', 'patients_at_risk',
      'barriers_resolved', 'evaluations_renewed_on_time',
    ];
    for (const key of deltaKeys) {
      const curr = current[key] || 0;
      const prev = previous[key] || 0;
      trends[key] = { current: curr, previous: prev, delta: curr - prev };
    }
  }

  return {
    current,
    trends,
    historicalSnapshots: historical,
    lastSnapshotDate: previous?.snapshot_date || null,
  };
}

module.exports = {
  computeOutcomesSnapshot,
  saveSnapshot,
  getSnapshots,
  getLatestSnapshot,
  getDashboard,
};
